stages:
  - build
  - test
  - check

variables:
  GNATFORMAT_DATE: 20260510

include:
  # Issue check
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/check-issue@~latest
    inputs:
      stage: check

  # gnatformat check
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/gnatformat@main
    inputs:
      stage: check
      anod-spec: aunit
      gnatformat-args: -P lib/gnat/aunit.gpr --check
      install-gnatformat: true
      install-gnatformat-extra-anod-args: -Qdate=$GNATFORMAT_DATE

  # Build
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/build@~latest
    inputs:
      stage: build
      job-name: build
      anod-args: build aunit
      cpus: 16
      image: pe-base
      save-component: true

  # Testing
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/test@~latest
    inputs:
      needs: ["build:linux"]
      job-name: aunit
      anod-args: test aunit
      image: pe-base
      cpus: 16
      disk: 80

aunit:linux:
  after_script:
    - cat /tmp/ci_env.sh
    - . /tmp/ci_env.sh
    - TEST_BSN=$(anod eval --primitive=test aunit build_space_name --sandbox-dir=$ANOD_DEFAULT_SANDBOX_DIR)
  artifacts:
    paths:
      - xunit-*.xml

    reports:
      junit: xunit-*.xml
