stages:
  - build
  - test
  - check

variables:
  GNATFORMAT_DATE: 20260510

include:
  # Issue check
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/check-issue@~latest
    inputs:
      stage: check

  # gnatformat check
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/gnatformat@main
    inputs:
      stage: check
      anod-spec: aunit
      gnatformat-args: -P lib/gnat/aunit.gpr --check
      install-gnatformat: true
      install-gnatformat-extra-anod-args: -Qdate=$GNATFORMAT_DATE

  # Build
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/build@~latest
    inputs:
      job-name: build
      anod-args: build aunit
      cpus: 16
      image: pe-base
      save-component: true

  # Cross build
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/build@~latest
    inputs:
      job-name: build-cross
      anod-args: build aunit --target aarch64-elf
      cpus: 16
      image: pe-base
      save-component: true

  # Testing
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/test@~latest
    inputs:
      needs: ["build:linux"]
      job-name: aunit
      anod-args: test aunit --minimal
      image: pe-base
      cpus: 16
      disk: 80

  # Cross testing
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/test@~latest
    inputs:
      needs: ["build-cross:linux"]
      job-name: aunit-cross
      anod-args: test aunit --minimal --target aarch64-elf,,qemu-zynqmp -Qrts=light-zynqmp
      image: pe-base
      cpus: 16
      disk: 80

aunit:linux:
  artifacts:
    paths:
      - xunit-*.xml

    reports:
      junit: xunit-*.xml

aunit-cross:linux:
  artifacts:
    paths:
      - xunit-*.xml

    reports:
      junit: xunit-*.xml
